### ISSUE TITLE
Utworzenie komend obecnych w v2

### ISSUE THREAD

**Issue by ghost** [kuvuBot/kuvuBot4#2]
- [x] Komenda `.awatar [wzmianka]` - zwraca awatar podanego użytkownika.
- [x] Komenda `.bot` - wyświetla informacje o bocie (nazwa, wersja, ilość serwerów, lista pierwszych dziesięciu serwerów, itp.).
- [x] Komenda `.emtekst <tekst>` - generuje tekst używając emotikon `:regional_indicator_x:`.
- [x] Komenda `.figlet <tekst>` - generuje figleta.
- [x] Komenda `.kot` - wyświetla losowego kota.
- [x] Komenda `.minecraft <ip>` - wyświetla status podanego serwera Minecraft.
- [x] Komenda `.mojang` - wyświetla status Mojangu.
- [x] Komenda `.pomoc`- wyświetla listę komend.
- [x] Komenda `.reaguj <tekst>` - reaguje podanym tekstem na podaną wiadomość.
- [x] Komenda `.serwer` - wyświetla informacje o aktualnym serwerze.
- [x] Komenda `.zapytaj <wiadomość>` - zadaje podane pytanie.
- [x] Komenda `.zdelegalizować <tekst>` - zwraca obrazek z isnowillegal.com ([więcej informacji tutaj](https://github.com/ivanseidel/Is-Now-Illegal/issues/20)).

**Comment by tboba** [comment]
Jak miałoby działać .reaguj?

W sensie, no okej. Podajesz tekst, jakim ma reagować bot. Ale - jaki tekst? Powyżej wiadomości?
Co zrobicie z powieleniem się reakcji, oraz spacjami?

**Comment by ghost** [comment]
@IceMeltt ma reagować tylko korzystając ze znaków należących do alfabetu łacińskiego, resztę znaków ma ignorować. Jeśli zareagował już jakimś znakiem to ma po prostu go pominąć.
