### ISSUE TITLE
Ciekawa, motywująca komenda + cytaty

### ISSUE THREAD

**Issue by tboba** [kuvuBot/kuvuBot4#6]
Hmm, co powiecie na komendy, której nie ma jeszcze w żadnym (przynajmniej polskim) bocie?

Mianowicie:

1. Komenda `.motivation` / `.motywacja` - wyśle losowe video / cytat motywacyjne.
2. Komenda `.cytat` - wyśle losowy cytat, stworzony przez mądrych ludzi. Jak Jan Paweł II, Juliusz Słowacki, Steve Jobs, i tak dalej.
3. Komenda `.clatin` / `.cłacina` - wyśle mądry cytat po łacinie. Typu `per aspera ad astra`, `ora et labora`.

**Comment by ghost** [comment]
Czy byłbyś w stanie podać jakieś miejsce z którego można by w prosty sposób pobierać takowe cytaty?

**Comment by tboba** [comment]
http://jastrzebie-gramatyki.pl/ :kappa:

A tak serio, trzeba by było raczej ręcznie wpisywać takie cytaty 😕 
Ewentualnie, jest jeszcze https://cytaty.pl/kategorie, albo też http://lubimyczytac.pl/cytaty.

**Comment by ghost** [comment]
Niestety, ale nie udało mi się znaleźć żadnego API, udostępniającego cytaty w języku polskim.
